### ISSUE TITLE
How to use Access Token in Down Stream API calls? 

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Blazorade/Blazorade-MSAL#17]
Blazorade-MSAL has made authenticating super easy - so thank you for creating this great library. 

However, I'm wondering what you would suggest in being able to use the Access Token for downstream API requests. 
(I am using Blazor Server w/ .net6). My API requests live in a Scoped service and and I seem to loose all session state when I navigate to another page, (and I have to use the "force" flag to even get it to navigate to the page). This leaves me with using ProtectedLocalStorage where I can get the auth information. 

I have tried everything outlined [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/?view=aspnetcore-6.0), and then  the Blazor Server specific stuff at [Secure ASP.NET Core Blazor Server apps](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/server/?view=aspnetcore-6.0&tabs=visual-studio), but these approaches didn't  even work for me when I was using the project template to generate a project using Microsoft Identity, (not using Blazorade-MSAL). 

Just wondering if you, or anyone else can suggest the proper technique. 

I have studied https://docs.microsoft.com/en-gb/aspnet/core/blazor/state-management?view=aspnetcore-6.0&pivots=server and it seems I that since upon every page navigation that a new session is being created, I have to rely on persisting in browser local storage. 

Am I missing something?

**Comment by MikaBerglund** [comment]
I thought I'd update the Blazorade MSAL library and make sure it works with .NET6 and MAUI. I could at the same time add an example of how you can acquire an access token for Microsoft Graph and use that for accessing it.

I guess that would be adequate for your purposes?

**Comment by AmitBhatnagar24** [comment]
@MikaBerglund  yes, I think that would indeed help, and would be greatly appreciated.

**Comment by AmitBhatnagar24** [comment]
or more specifically.. .an update to .net6 and sample that illustrates how we can use `<CascadingAuthenticationState>` (if this would still make sense when authenticating with Blazorade rather than when using the MS ID scaffolding) to share the authentication token for downstream API requests. 

Obviously the technique outlined [Pass tokens to a Blazor Server app](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-6.0) doesn't work... so what is the alternative when using Blazorade-msal?

**Comment by MikaBerglund** [comment]
The [Graph Client](https://github.com/Blazorade/Blazorade-MSAL/tree/main/GraphClient) sample is now updated to use the new [`BlazoradeRequestFactory`](https://github.com/Blazorade/Blazorade-MSAL/blob/main/Blazorade.Msal/Services/BlazoradeRequestFactory.cs) that I've added in #20.

I'll close the issue for now, but feel free to open it should you have any further questions in the subject.
