### ISSUE TITLE
Support mocking BlazoradeMsalService

### ISSUE THREAD

**Issue by HolisticDeveloper** [Blazorade/Blazorade-MSAL#23]
I'd like to be able to unit test my components that utilize BlazoradeMsalService. Can the methods be made virtual so that they can be overridable?

**Comment by MikaBerglund** [comment]
I'll look into that, but I see no reason why not. I guess the correct way would be to define an interface that is used when injecting.

**Comment by MikaBerglund** [comment]
I guess the easier way would be to set all methods on the `BlazoradeMsalService` to virtual so that they can all be overridden for testing purposes. So, if that's OK with you, I guess that's what I'll do for now.

**Comment by MikaBerglund** [comment]
There is now a PR #24 waiting. If that would be enough for your needs @HolisticDeveloper, I can go ahead and complete the PR and publish a new version to Nuget.
